In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [2]:
# libraries import 
import tensorflow as tf

In [3]:
# Initialization of Tensors
x = tf.constant(4) # It's scalar value with int value
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
x = tf.constant(4.0) # It's scalar value with float value
print(x)

tf.Tensor(4.0, shape=(), dtype=float32)


In [5]:
x = tf.constant(4, shape=(1, 1)) # It's scalar value with shape parameter
print(x)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [6]:
x = tf.constant(4, shape=(1, 1), dtype=tf.float32) # It's scalar value with shape parameter and dtype
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [7]:
x = tf.constant([[1, 2, 3], [4, 5, 6]]) # It's multidimension tensor
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
x = tf.ones((2, 2)) # It auto generate multidimension tensor with value containing 1 in it.
print(x)

tf.Tensor(
[[1. 1.]
 [1. 1.]], shape=(2, 2), dtype=float32)


In [9]:
x = tf.zeros((3, 3)) # It auto generate multidimension tensor with value containing 0 in it.
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [10]:
x = tf.eye(3) # It auto generate multidimension tensor like identity matries.
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
x = tf.random.normal((3, 4), mean=0, stddev=1) # It's time to create tensor with values are distribute normally (standard normal distribution)
print(x)

tf.Tensor(
[[ 0.14966665 -0.86145794  1.3797591  -0.3800322 ]
 [-0.8114309  -0.08147749  0.3248987   0.57307094]
 [-0.23579396  1.2053285   0.4674581   0.76564264]], shape=(3, 4), dtype=float32)


In [12]:
x = tf.random.uniform((2, 2), minval=0, maxval=1) # It's time to create tensor with values are distribute uniformly
print(x)

tf.Tensor(
[[0.99371076 0.6210977 ]
 [0.96073294 0.8409959 ]], shape=(2, 2), dtype=float32)


In [13]:
x = tf.range(9) # It works just like python range method
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)


In [14]:
x = tf.range(start=1, limit=20, delta=2) # It can be used for generating large size vectors
print(x)

tf.Tensor([ 1  3  5  7  9 11 13 15 17 19], shape=(10,), dtype=int32)


In [15]:
x = tf.cast(x, dtype=tf.float32) # Type casting tensor
print(x)

tf.Tensor([ 1.  3.  5.  7.  9. 11. 13. 15. 17. 19.], shape=(10,), dtype=float32)


In [16]:
# Mathrmatical operations
x = tf.constant([1, 2, 3])
y = tf.constant([9, 8, 7])

z1 = tf.add(x, y) # Element wise addition
z2 = x + y # same operation with different way of performing
print(z1)
print(z2)

tf.Tensor([10 10 10], shape=(3,), dtype=int32)
tf.Tensor([10 10 10], shape=(3,), dtype=int32)


In [17]:
z1 = tf.subtract(x, y) # Element wise substraction
z2 = x - y # same operation with different way of performing
print(z1)
print(z2)

tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)
tf.Tensor([-8 -6 -4], shape=(3,), dtype=int32)


In [18]:
z1 = tf.divide(x, y) # Element wise division
z2 = x / y # same operation with different way of performing
print(z1)
print(z2)

tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)
tf.Tensor([0.11111111 0.25       0.42857143], shape=(3,), dtype=float64)


In [19]:
z1 = tf.multiply(x, y) # Element wise multiplcation
z2 = x * y # same operation with different way of performing
print(z1)
print(z2)

tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)
tf.Tensor([ 9 16 21], shape=(3,), dtype=int32)


In [20]:
z1 = tf.tensordot(x, y, axes=1) # Dot product
z2 = tf.reduce_sum(x * y, axis=0) # same operation with different way of performing
print(z1)
print(z2)

tf.Tensor(46, shape=(), dtype=int32)
tf.Tensor(46, shape=(), dtype=int32)


In [21]:
z1 = x ** y # Exponential
print(z1)

tf.Tensor([   1  256 2187], shape=(3,), dtype=int32)


In [22]:
x = tf.random.normal((2, 3))
y = tf.random.normal((3, 4))

z1 = tf.matmul(x, y)
z2 = x @ y
print(z1)
print(z2)

tf.Tensor(
[[-5.518953   -0.80757856 -3.7021523  -3.3565936 ]
 [ 0.54536015  0.36742184 -0.43433708  0.08798856]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[-5.518953   -0.80757856 -3.7021523  -3.3565936 ]
 [ 0.54536015  0.36742184 -0.43433708  0.08798856]], shape=(2, 4), dtype=float32)


In [23]:
# Indexing
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
print(x[:]) # print everything
print(x[1:]) # print starting from 1st index
print(x[1:3]) # print 1st and 2nd element
print(x[::2]) # print every alternate element
print(x[::-1]) # print in reverse order

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [24]:
x = tf.constant([0, 1, 1, 2, 3, 1, 2, 3])
indices = tf.constant([1, 6])
x_index = tf.gather(x, indices) # Collect only 1st, 6th position data
print(x_index)

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [25]:
x = tf.constant([[1, 2],
                [3, 4],
                [5, 6]])
print(x[0, :]) # Access everything from 1st row
print(x[0:2, :]) # Access everything from 1st and 2nd row
print(x[:, 0]) # Access everything from 1st column

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [26]:
# Reshaping
x = tf.range(9)
print(x)
x = tf.reshape(x, (3, 3)) # Reshape vector to matrix
print(x)

tf.Tensor([0 1 2 3 4 5 6 7 8], shape=(9,), dtype=int32)
tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)


In [27]:
x = tf.transpose(x, perm=[1, 0]) # Swap rows to columns
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)
